name: the_powder_room_guys
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  timelines: ^0.1.0
  flutter_rating_bar: ^4.0.1
  flutter_switch: ^0.3.2
  expandable: ^5.0.1
  step_progress_indicator: ^1.0.2
  dropdown_button2: ^1.9.2
  textfield_tags: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: poppins
      fonts:
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700


    - family: sf_ui_display
      fonts:
        - asset: fonts/sf_ui_display/sf_ui_display_ultralight.otf
          weight: 200
        - asset: fonts/sf_ui_display/sf_ui_display_thin.otf
          weight: 300
        - asset: fonts/sf_ui_display/sf_ui_display_regular.otf
          weight: 400
        - asset: fonts/sf_ui_display/sf_ui_display_medium.otf
          weight: 500
        - asset: fonts/sf_ui_display/sf_ui_display_semibold.otf
          weight: 600
        - asset: fonts/sf_ui_display/sf_ui_display_bold.otf
          weight: 700


    - family: sf_compact
      fonts:
        - asset: fonts/sf_compact_text/SF_Compact_Text_Thin.ttf
          weight: 300
        - asset: fonts/sf_compact_text/SF_Compact_Text_Regular.ttf
          weight: 400
        - asset: fonts/sf_compact_text/SF_Compact_Text_Medium.ttf
          weight: 500
        - asset: fonts/sf_compact_text/SF_Compact_Text_Bold.ttf
          weight: 700
