import 'package:the_powder_room_guys/controller/admin_controller/admin_auth_controller/admin_auth_controller.dart';
import 'package:the_powder_room_guys/controller/guest_controller/guest_auth_controller/guest_auth_controller.dart';
import 'package:the_powder_room_guys/controller/member_controller/member_auth_controller/member_sign_up_controller.dart';

//GETX INSTANCES
GuestAuthController guestSignController = GuestAuthController.instance;
MemberAuthController memberAuthController = MemberAuthController.instance;
AdminAuthController adminAuthController = AdminAuthController.instance;
